config/routes.rb
Spree::Core::Engine.routes.draw do
     
    namespace :admin do
        get "futurepay/index" => "futurepay#index"
        put "futurepay/create" => "futurepay#create"
        get "futurepay/create" => "futurepay#create"
    end
    
    get "checkout/payment/futurepay/confirm" => "futurepay#confirm"
      
    post "checkout/payment/futurepay" => "futurepay#preorder"
    
  namespace :admin do
    # Using :only here so it doesn't redraw those routes
    resources :orders, :only => [] do
      resources :payments, :only => [] do
        member do
          get 'futurepay_refund'
          post 'futurepay_refund'
        end
      end
    end
  end
  
  
end

app/models/spree/payment_method/futurepay.rb
module Spree

  class PaymentMethod::Futurepay < PaymentMethod

    preference :gmid, :string

    def gmid   
      return  preferred_gmid      
    end

    def confirm_url
      "payment/futurepay/confirm" 
    end

    def preOrderUrl
      "payment/futurepay"
    end

    def can_void?(payment)
      false
    end

    def auto_capture?
      true
    end
    
    def can_credit?(payment)
      false
    end

    def purchase(amount, source, gateway_options = {})
      
      Class.new do
        def success?; true; end
        def authorization; nil; end
      end.new

      ActiveMerchant::Billing::Response.new(true, "FuturePay Purchase Successful",{:amount => amount, :transaction_id => source[:transaction_id], :result => source[:code], :created_at => source[:created_at]},{})

    end
    

  def refund(payment, amount)

      require 'uri'
      require 'net/http'   
      
      #send pre-order request for cart token
      refund_type = payment.amount == amount.to_f ? "Full" : "Partial"
      order = Spree::Order.find_by_id(payment[:order_id])
      fp = PaymentMethod::Futurepay.last()
        if fp.environment == "production"
          uri = URI.parse('https://api.futurepay.com/remote/merchant-returns')
          gmid = fp.gmid
        else
          uri = URI.parse('https://demo.futurepay.com/remote/merchant-returns')
          gmid = "882bb39add08c23107753012b2917bfd1bb28bf8FPM975056"
        end

      refund_params = { 
                 "gmid"  => gmid,
                 "reference"  => order[:number],
                 "total_price"  => amount
                 }

      http = Net::HTTP.new(uri.host, uri.port)        
      http.use_ssl = true
      if fp.environment == "production"
        http.verify_mode = OpenSSL::SSL::VERIFY_PEER
      else
        http.verify_mode = OpenSSL::SSL::VERIFY_NONE
      end
      request = Net::HTTP::Post.new(uri.request_uri)
      request.set_form_data(refund_params)
      response = http.request(request)   
      result = ActiveSupport::JSON.decode(response.body.strip) 

      
        if result['status'] == "FP_REFUND_SUCCESSFUL"          
          
          payment.class.create!({
              :source => Spree::FuturepayCheckout.create({
              :transaction_id => result['TransactionReference'],
              :code => result['status'],
              :total => amount.to_f
            }),
            :order => payment.order,
            :payment_method => fp,
            :amount => amount.to_f.abs * -1,
            :response_code => result['TransactionReference'],
            :state => 'completed'
          })

        else
      
          payment.class.create!({
              :source => Spree::FuturepayCheckout.create({
              :code => result['status'],
              :total => amount.to_f
            }),
            :order => payment.order,
            :payment_method => fp,
            :amount => amount.to_f.abs * -1,
            :response_code => result['status'],
            :state => 'failed'
          })
      
        end
      result
    end
  end
end

app/controllers/spree/admin/futurepay_controller.rb
module Spree
  module Admin
    class FuturepayController < Spree::Admin::BaseController


      def index
        
      end

      def create                                   

      require 'uri'
      require 'net/http'  
        
        uri = URI.parse('https://api.futurepay.com/remote/merchant-request-key')
        if params[:selected_state_code].present?
          params[:region_code] = Spree::State.find(params[:selected_state_code][:id]).abbr
        end
        if params[:selected_state_name].present?
          params[:region_code] = params[:selected_state_name][:id]
        end

        
        if params[:type] == "signup"
          params[:country_code] = Spree::Country.find(params[:selected_country][:id]).iso
        end
        request_params = params
        http = Net::HTTP.new(uri.host, uri.port)        
        http.use_ssl = true
        http.verify_mode = OpenSSL::SSL::VERIFY_PEER
        request = Net::HTTP::Post.new(uri.request_uri,)
        request.set_form_data(request_params)
        response = http.request(request)     
        result = JSON.parse(response.body)
        # search the api response for an error code


        if result["error"] == 1

          flash.notice = result["message"]
          redirect_to admin_futurepay_index_path and return  

        else

            fp = Spree::PaymentMethod::Futurepay.last()

            if fp.instance_of?(PaymentMethod::Futurepay)
             #set the gmid for the existing futurepay payment method (if it exists)
             fp.preferred_gmid    = result["key"]
             fp.save       

            flash[:success] = result["message"]
            redirect_to admin_futurepay_index_path and return  

            else
              #create new futurepay payment method
              new_fp = PaymentMethod::Futurepay.new()
              new_fp.type              = "Spree::PaymentMethod::Futurepay"
              new_fp.name              = "FuturePay"
              new_fp.description       = "Buy now and pay later."
              new_fp.active            = true
              new_fp.environment       = "production"
              new_fp.preferred_gmid    = result["key"]
              new_fp.save

              flash[:success] = "FuturePay has succesfully been added as a Payment Method and is ready to start taking orders."
              redirect_to admin_futurepay_index_path and return     

            end
        end                              
      end                       
    end
  end
end

app/controllers/spree/futurepay_controller.rb
module Spree
  class FuturepayController < Spree::StoreController

    def success
      
    end
    
    def preorder
      require 'uri'
      require 'net/http'
      @order = current_order
      billing_address = Spree::Address.find(@order.bill_address_id)
      shipping_address = Spree::Address.find(@order.ship_address_id)
      country = Spree::Country.find(billing_address.country_id)
      country = country.iso

      fp = PaymentMethod::Futurepay.last()
      #send pre-order request for cart token
      respond_to do |format|
        if @order.currency == "USD" && country == "US"
          state = Spree::State.find(billing_address.state_id)
          shippingCountry = Spree::Country.find(shipping_address.country_id)
          shippingCountry = shippingCountry.iso

          if shipping_address.state_id.present?
            shippingState = Spree::State.find(shipping_address.state_id)
          else
            shippingState = shipping_address.state_name
          end

          shippingCountry = shippingState.country().iso
          fp = PaymentMethod::Futurepay.last()

          if fp.environment == "production"
            uri = URI.parse('https://api.futurepay.com/remote/merchant-request-order-token')
            script_url = "https://api.futurepay.com/remote/cart-integration/"
            gmid = fp.gmid
          else
            uri = URI.parse('https://demo.futurepay.com/remote/merchant-request-order-token')
            script_url = "https://demo.futurepay.com/remote/cart-integration/"
            gmid = "882bb39add08c23107753012b2917bfd1bb28bf8FPM975056"
          end

          preorder_params = { "gmid" => gmid,
                     "first_name" => billing_address.firstname,
                     "last_name"  => billing_address.lastname,
                     "address_line_1" => billing_address.address1,
                     "city" => billing_address.city,
                     "state"  => state.abbr,
                     "country" => country,
                     "zip" => billing_address.zipcode,
                     "phone" => billing_address.phone,
                     "shipping_address_line_1" => shipping_address.address1,
                     "shipping_city" => shipping_address.city,
                     "shipping_state"  => shippingState.abbr,
                     "shipping_country" => shippingCountry,
                     "shipping_zip" => shipping_address.zipcode,
                     "reference" => @order.number,
                     "email" => @order.email,
                     "sku[0]" => "Complete Order",
                     "price[0]" => @order.total,
                     "tax_amount[0]" => 0,
                     "description[0]" => "Total cost of Order",
                     "quantity[0]" => 1
                     }

          http = Net::HTTP.new(uri.host, uri.port)        
          http.use_ssl = true
          if fp.environment == "production"
            http.verify_mode = OpenSSL::SSL::VERIFY_PEER
          else
            http.verify_mode = OpenSSL::SSL::VERIFY_NONE
          end
          request = Net::HTTP::Post.new(uri.request_uri)
          request.set_form_data(preorder_params)
          response = http.request(request)   
          result = response.body.strip

          error_message_found = result.include?("FP_")

          if error_message_found
            if  result.include?("MISSING_REQUIRED_PHONE") 
                result = "There was no phone number entered for your billing address. Please enter a phone number and try again."
            elsif result.include?("NO_ZIP_FOUND") 
                result = "The Zip code you entered for your billing address corresponds to a Military (APO/FPO/DPO), PO Box or other non-physical address. To approve your application we require a Zip code associated with a physical address in the U.S.";
            elsif result.include?("INVALID_TOTAL_TRANSACTION_AMOUNT")
                result = "Your purchase was not successful because the total amount is $0. Please check your cart to ensure items have been added and try again.";
            elsif result.include?("INVALID_EMAIL_FORMAT")
                result = "The email address entered is not valid, please re-enter and try again.";
            elsif result.include?("INVALID_STATE_ZIP_COMBINATION")
                result = "The Zip code does not match the state entered. Please re-enter and try your purchase again.";
            elsif result.include?("INVALID_MERCHANT_STATUS")
                result = "We are unable to process your order with the Merchant. No charges have been applied to your FuturePay tab. Please contact the Merchant for assistance in completing your order. We apologize for any inconvenience this may have caused.";
            elsif result.include?("EXISTING_INVALID_CUSTOMER_STATUS")
                result = "Your purchase was not successful because your account is not in an active state. Please contact FuturePay at support@futurepay.com";
            elsif result.include?("INVALID_SERVER_REQUEST")
                result = "We are unable to process your order with the Merchant. No charges have been applied to your FuturePay tab. Please contact the Merchant for assistance in completing your order. We apologize for any inconvenience this may have caused.";
            elsif result.include?("PRE_ORDER_EXCEEDS_MAXIMUM")
                result = "This order exceeds the maximum available amount on a FuturePay account.";
            else
                result = "There was a problem creating your order. No changes have been applied to your FuturePay tab. Please contact FuturePay at support@futurepay.com";
            end
          else
            result = script_url + result
          end
        else
          result = "FuturePay is only available for Payments in US Dollars, for American residents.";
        end        
        format.json { render :json => result } 
      end
    end
    
    
    
    def confirm
      purchase_result = ActiveSupport::JSON.decode(params[:info])
      order = current_order
      fp = PaymentMethod::Futurepay.last()

      if purchase_result['transaction_id'].present?

          if fp.environment == "production"
            uri = URI.parse('https://api.futurepay.com/remote/merchant-order-verification')
            gmid = fp.gmid
          else
            uri = URI.parse('https://demo.futurepay.com/remote/merchant-order-verification')
            gmid = "882bb39add08c23107753012b2917bfd1bb28bf8FPM975056"
          end

        params = { "gmid" => gmid,
                   "otxnid" => purchase_result['transaction_id']
                   }        
        http = Net::HTTP.new(uri.host, uri.port)        
        http.use_ssl = true
          if fp.environment == "production"
            http.verify_mode = OpenSSL::SSL::VERIFY_PEER
          else
            http.verify_mode = OpenSSL::SSL::VERIFY_NONE
          end
        request = Net::HTTP::Post.new(uri.request_uri)
        request.set_form_data(params)
        response = http.request(request)     
        order_verification_result = ActiveSupport::JSON.decode(response.body.strip)   
        
      else
       #the response from fp is that the sale was nto successful, errors should be displayed here 
       flash.notice = Spree.t(:payment_processing_failed)
       redirect_to checkout_state_path(order.state) and return        

      end
      #this is the verify api check
      if order_verification_result['OrderStatusCode'] == "ACCEPTED"
                               
          order = current_order || raise(ActiveRecord::RecordNotFound)
          payment = order.payments.last
          payment.update_attributes!({
              :source => Spree::FuturepayCheckout.create({
              :transaction_id => order_verification_result['OrderReference'],
              :code => order_verification_result['OrderStatusCode'],
              :total => order_verification_result['TotalPrice'].to_f
            }),
            :response_code => order_verification_result['OrderStatusCode'],
            :amount => order.total,
            :payment_method => fp
          })

         order.next   

        if order.complete?
          flash.notice = Spree.t(:order_processed_successfully)
          session[:order_id] = nil
          redirect_to order_path(order, :token => order.guest_token)
        else
          redirect_to checkout_state_path(order.state)
        end
                       
      else
        flash.notice = "The FuturePay payment was not successful."
        redirect_to order_path(order, :token => order.guest_token)
      end            
    end      
  end
end

app/views/spree/admin/futurepay/index.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= "FuturePay Integration" %>
<% end %>

<%= javascript_include_tag "futurepay.js" %>
<% opts ||= Spree::Address.new(country: Spree::Country.new) %>
<% s_or_b = "s" %>

<div id="futurepay-intro" class="field">
  
  With FuturePay, shoppers don't need a credit card to buy from your online store.  They simply put their purchases on a FuturePay tab, making it easy to buy now and pay later. 
  Offering another payment method, like FuturePay, attracts new customers and leads to more sales.<br /><br /><br />
  
  If you already have a FuturePay merchant account, click the button below and enter your FuturePay login credentials when prompted.  Then, FuturePay will be an available payment option for shoppers in your store<br /><br />
  
  <div class="align-center">
    <input type="button" id="activate-fp" value="Activate FuturePay"><br /><br />
  </div>
  
  If you don't have a FuturePay merchant account, add FuturePay to your cart in minutes.<br /><br />
  
  <div class="align-center">
    <input type="button" id="create-fp" value="Get Started Now">
  </div>
  
</div>

   <div class="row">
        <div id="futurepay-new" class="alpha six columns">
          <fieldset class="create no-border-bottom">
            <legend align="center"><%= Spree.t(:get_started_now)%></legend>
              <%= form_tag admin_futurepay_create_path, :method => :put do |f| %>
            

            
                <div class="field">
                  <%= label_tag :contact_email, Spree.t(:contact_email) %> <br />
                  <%= text_field_tag :contact_email, "", :required => true ,:maxlength => 45, :class => 'fullwidth' %><br>
                  <span class="info">
                    <%= Spree.t(:account_email_address) %>
                  </span>
                </div>              
            
                <div class="field">
                  <%= label_tag :first_name, Spree.t(:first_name) %> <br />
                  <%= text_field_tag :first_name, "", :required => true ,:maxlength => 45, :class => 'halfwidth' %><br>
                </div>
            
                <div class="field">
                  <%= label_tag :last_name, Spree.t(:last_name) %> <br />
                  <%= text_field_tag :last_name, "", :required => true ,:maxlength => 45, :class => 'halfwidth' %><br>
                </div>
            
                <div class="field">
                  <%= label_tag :main_phone, Spree.t(:main_phone) %> <br />
                  <%= text_field_tag :main_phone, "", :required => true ,:maxlength => 45, :class => 'halfwidth' %><br>
                  <span class="info">
                    <%= Spree.t(:primary_business_contact) %>
                  </span>
                </div>  

                <div class="field">
                  <%= label_tag :name, Spree.t(:name) %> <br />
                  <%= text_field_tag :name, "", :required => true ,:maxlength => 45, :class => 'fullwidth' %><br>
                </div>  

                <div class="field">
                  <%= label_tag :website, Spree.t(:website) %> <br />
                  <%= text_field_tag :website, "", :required => true ,:maxlength => 45, :class => 'fullwidth' %><br>
                </div>            
                <div class="field">
                  <%= label_tag :state, Spree.t(:country) %> <br />
                  <span id="<%= s_or_b %>country">
                    <%= collection_select(:selected_country,:id, available_countries, :id , :name, {}, {:class => 'select2 fullwidth',:required => true}) %>
                  </span>
                </div>
                <div class="field">
                  <%= label_tag :state, Spree.t(:state) %> <br />
                  <span id="<%= s_or_b %>state">
                    <%= text_field :selected_state_name,:id,:style => "display: #{opts.country.states.empty? ? 'block' : 'none' };",:maxlength => 45,:disabled => opts.country.states.empty?,:required => true, :class => 'fullwidth state_name' %>
                    <%= collection_select(:selected_state_code,:id, opts.country.states.sort, :id, :name, {:include_blank => true}, {:class => 'select2 fullwidth', :required => true,:style => "display: #{opts.country.states.empty? ? 'none' : 'block' };", :disabled => opts.country.states.empty?}) %>
                  </span>
                </div>
                <div class="field">
                  <%= label_tag :address, Spree.t(:address) %> <br />
                  <%= text_field_tag :address, "", :required => true ,:maxlength => 45, :class => 'fullwidth' %><br>
                </div>  

                <div class="field">
                  <%= label_tag :city, Spree.t(:city) %> <br />
                  <%= text_field_tag :city, "", :required => true ,:maxlength => 45, :class => 'halfwidth' %><br>
                </div>  

                <div class="field">
                  <%= label_tag :zip, Spree.t(:zip) %> <br />
                  <%= text_field_tag :zip, "", :required => true ,:maxlength => 45, :class => 'halfwidth' %><br>
                </div>  

                  <%= text_field_tag :type,"signup", :required => true ,:maxlength => 45, :class => 'hidden' %>
                  <%= button Spree.t('actions.create_account_and_activate'), 'refresh' %>  <a id="create-fp-close">CANCEL</a>
              
              <% end %>
          </fieldset>
        </div>
        <div id="futurepay-existing" class="alpha six columns">
          <fieldset class="create no-border-bottom">
            <legend align="center"><%= Spree.t(:activate_futurepay)%></legend>
              <%= form_tag admin_futurepay_create_path, :method => :put do |f| %>

                <div class="field">
                  <%= label_tag :user_name, Spree.t(:user_name) %> <br />
                  <%= text_field_tag :user_name, "", :required => true ,:maxlength => 45, :class => 'fullwidth' %><br>
                  <span class="info">
                    <%= Spree.t(:account_email_address) %>
                  </span>
                </div>                          
                <div class="field">
                  <%= label_tag :password, Spree.t(:password) %> <br />
                  <%= password_field_tag :password, "", :required => true ,:maxlength => 45, :class => 'fullwidth' %><br>
                  <span class="info">
                    <%= Spree.t(:account_password) %>
                  </span>
                </div>  

                  <%= text_field_tag :type,"retrieve", :required => true ,:maxlength => 45, :class => 'hidden' %>
                  <%= button Spree.t('actions.activate_futurepay'), 'refresh' %>  <a id="activate-fp-close">CANCEL</a>
            
              <% end %>
          </fieldset>
        </div>
   </div>

  
  
<% content_for :head do %>
  <%= javascript_tag do -%>
    $(document).ready(function(){
      $('span#<%= s_or_b %>country .select2').on('change', function() { update_state('<%= s_or_b %>'); });
    });
  <% end -%>
<% end %>
  