config/routes.rb
Spree::Core::Engine.routes.draw do
     
    namespace :admin do
        get "futurepay/index" => "futurepay#index"
        put "futurepay/create" => "futurepay#create"
        get "futurepay/create" => "futurepay#create"
    end
    
    get "checkout/payment/futurepay/confirm" => "futurepay#confirm"
      
    post "checkout/payment/futurepay" => "futurepay#preorder"
    
  namespace :admin do
    # Using :only here so it doesn't redraw those routes
    resources :orders, :only => [] do
      resources :payments, :only => [] do
        member do
          get 'futurepay_refund'
          post 'futurepay_refund'
        end
      end
    end
  end
  
  
end

app/views/spree/admin/payments/futurepay_refund.html.erb
<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Payments' } %>

<% content_for :page_title do %>
  <i class="icon-arrow-right"></i>
  <%= link_to Spree.t(:payments), admin_order_payments_path(@order) %>
  <i class="icon-arrow-right"></i>
  <%= payment_method_name(@payment) %>
  <i class="icon-arrow-right"></i>
  <%= "Refund" %>
<% end %>

<%= form_tag futurepay_refund_admin_order_payment_path(@order, @payment) do %>
  <div class="label-block left five columns alpha">
    <div>
      <fieldset data-hook="admin_variant_new_form">
        <legend>Refund</legend>
        <div class='field'>
          <%= label_tag 'refund_amount', Spree.t(:refund_amount, :scope => 'futurepay') %>
          <small><em>Original amount</em></small><br>
          <% symbol = ::Money.new(1, Spree::Config[:currency]).symbol %>
          <% if Spree::Config[:currency_symbol_position] == "before" %>
            <%= symbol %><%= text_field_tag 'refund_amount', @payment.amount %>
          <% else %>
            <%= text_field_tag 'refund_amount', @payment.amount %><%= symbol %>
          <% end %>
        </div>
        <%= button "Refund", 'icon-dollar' %>
      </fieldset>
    </div>
  </div>
<% end %>